parameters:
#    event.example.class: Yoda\EventBundle\Example

services:
    yoda_event.reporting.event_report_manager:
        class: Yoda\EventBundle\Reporting\EventReportManager
        arguments:
            - "@doctrine.orm.default_entity_manager"
